{{- $values := $.Values.heimdall }}
{{- if $values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "heimdall.serviceAccountName" . }}
  labels:
    {{- include "heimdall.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "heimdall.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "heimdall.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
