{{- $values := $.Values.heimdall }}
{{- if $values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "heimdall.serviceAccountName" . }}
  labels:
    {{- include "heimdall.labels" . | nindent 4 }}
rules:
{{- toYaml $values.rbac.clusterRules | nindent 0 }}
{{- end }}
