{{- $values := $.Values.heimdall }}
{{- $componentName := "heimdall" }}
{{- $componentLabel := include "heimdall.componentLabelFor" $componentName }}
{{- if $values.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "heimdall.fullname" . }}-{{ $componentName }}
  labels:
    {{- include "heimdall.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ include "heimdall.p2pPort" . }}
      targetPort: p2p-tcp
      protocol: TCP
      name: p2p-tcp
    - port: {{ include "heimdall.p2pPort" . }}
      targetPort: p2p-udp
      protocol: UDP
      name: p2p-udp
    - port: {{ $values.httpPort }}
      targetPort: http-trpc
      protocol: TCP
      name: http-trpc
    - port: {{ $values.httpRest }}
      targetPort: http-rest
      protocol: TCP
      name: http-rest
    - port: {{ $values.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  {{- if $values.extraPorts }}
    {{ toYaml $values.extraPorts | nindent 4}}
  {{- end }}
  selector:
    {{- include "heimdall.selectorLabels" . | nindent 4 }}
{{- end }}
